[package]
name = "mnemos-x86_64-core"
version = "0.1.0"
edition = "2021"

[lib]
test = false
bench = false

[features]

[dependencies]
acpi = "4.1.1"
embedded-graphics = "0.7.1"

# kernel
[dependencies.mnemos]
path = "../../../source/kernel"
default-features = false

[dependencies.tracing]
version = "0.1.37"
features = ["attributes"]
default-features = false

[dependencies.hal-core]
git = "https://github.com/hawkw/mycelium"
default-features = false

[dependencies.hal-x86_64]
git = "https://github.com/hawkw/mycelium"

[dependencies.mycelium-util]
git = "https://github.com/hawkw/mycelium"


[dependencies.futures]
version = "0.3.21"
features = ["async-await"]
default-features = false