[workspace]
resolver = "2"
members = [
    # mnemOS source
    "source/kernel",
    "source/abi",
    "source/mstd",
    "source/spitebuf",
    "source/melpomene",
    "source/alloc",
    "source/forth3",

    # tools
    "tools/crowtty",
    "tools/dumbloader",
    "tools/f3repl",

    # platforms
    "platforms/allwinner-d1/drivers",
    "platforms/allwinner-d1/boards/lichee-rv",
]

[patch.crates-io.maitake]
git = "https://github.com/hawkw/mycelium.git"
rev = "d7e149bc0e1160136b2da4cee305f9aa99ecb7c6"

[patch.crates-io.cordyceps]
git = "https://github.com/hawkw/mycelium.git"
rev = "d7e149bc0e1160136b2da4cee305f9aa99ecb7c6"

[patch.crates-io.mnemos-alloc]
path = "./source/alloc"
