[workspace]
members = [
    # mnemOS source
    "source/kernel",
    "source/abi",
    "source/mstd",
    "source/spitebuf",
    "source/melpomene",

    # tools
    "tools/crowtty",
    "tools/dumbloader",
]

[patch.crates-io.modality-ingest-client]
git = "https://github.com/auxoncorp/modality-sdk"
rev = "4a3b9e3cca08e8225e084f9e8409e818646589ec"

[patch.crates-io.maitake]
git = "https://github.com/hawkw/mycelium.git"
rev = "5cb0341b2c7b91e8e01b26bedb6c4ce536e726b5"

[patch.crates-io.cordyceps]
git = "https://github.com/hawkw/mycelium.git"
rev = "5cb0341b2c7b91e8e01b26bedb6c4ce536e726b5"

[patch.crates-io.mnemos-alloc]
git = "https://github.com/tosc-rs/mnemos-alloc"
rev = "a1e1a56fd4665e059b74eacea8ea7fe14e4f32c4"
# path = "/home/james/tosc/mnemos-alloc"
