[workspace]
members = [
    # mnemOS source
    "source/kernel",
    "source/abi",
    "source/mstd",
    "source/spitebuf",
    "source/melpomene",
    "source/alloc",

    # tools
    "tools/crowtty",
    "tools/dumbloader",
]

[patch.crates-io.maitake]
git = "https://github.com/hawkw/mycelium.git"
rev = "5149ee6146a9e0c1af56da79bb55578abf6dfddc"

[patch.crates-io.cordyceps]
git = "https://github.com/hawkw/mycelium.git"
rev = "5149ee6146a9e0c1af56da79bb55578abf6dfddc"

[patch.crates-io.mnemos-alloc]
path = "./source/alloc"
