[package]
name = "forth3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hash32 = "0.3.1"

[features]
default = []
use-std = []

# [dependencies.serde]
# version = "1.0.152"
# default-features = false
# features = ["derive"]

# [dependencies.postcard]
# version = "1.0.2"
# default-features = false
