[workspace]
members = [
    # mnemOS source
    "source/kernel",
    "source/abi",
    "source/mstd",
    "source/spitebuf",
    "source/melpomene",

    # tools
    "tools/crowtty",
    "tools/dumbloader",
]

exclude = [
    "source/platforms/allwinner-d1",
]

[patch.crates-io.maitake]
git = "https://github.com/hawkw/mycelium.git"
rev = "cea81817e95b38f178feb05ae27d137bbd4e8e60"

[patch.crates-io.cordyceps]
git = "https://github.com/hawkw/mycelium.git"
rev = "cea81817e95b38f178feb05ae27d137bbd4e8e60"

[patch.crates-io.mnemos-alloc]
git = "https://github.com/tosc-rs/mnemos-alloc"
rev = "a1e1a56fd4665e059b74eacea8ea7fe14e4f32c4"
# path = "/home/james/tosc/mnemos-alloc"
