[package]
name = "mnemos-x86_64-bootloader"
version = "0.1.0"

[build-dependencies]
bootloader = "0.11"

[build-dependencies.mnemos]
package = "mnemos-x86_64"
path = "../kernel"
artifact = "bin:bootloader"
target = "x86_64-unknown-none"
features = ["bootloader_api"]

[dependencies]
# used for UEFI booting in QEMU
ovmf-prebuilt = "0.1.0-alpha.1"