[workspace]
resolver = "2"
members = [
    ".",
    "./d1-config",
]

[package]
name = "mnemos-d1"
version = "0.1.0"
edition = "2021"
description = """
A hardware abstraction library for the Allwinner D1, targeted
at use in the mnemos operating system.
"""
repository = "https://github.com/tosc-rs/mnemos"
homepage = "https://mnemos.dev"
readme = "./README.md"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
d1-config = { path = "./d1-config" }
serde = { version = "1.0.178", features = ["derive"] }
mnemos-config = { path = "../../source/config", features = ["use-std"] }
mnemos = { path = "../../source/kernel" }

[dependencies]
serde = { version = "1.0.178", features = ["derive"], default-features = false }
d1-config = { path = "./d1-config" }
mnemos-config = { path = "../../source/config" }

d1-pac = "0.0.31"
critical-section = "1.1.1"
riscv-rt = "0.11.0"

# kernel
[dependencies.mnemos]
path = "../../source/kernel"
default-features = false

[dependencies.mnemos-beepy]
path = "../beepy"

[dependencies.tracing]
version = "0.1.37"
features = ["attributes"]
default-features = false

[dependencies.embedded-graphics]
version = "0.7.1"

[dependencies.futures]
version = "0.3.21"
features = ["async-await"]
default-features = false

[dependencies.riscv]
version = "0.10"
features =[ "critical-section-single-hart"]

[features]
# board features
lichee-rv = []
mq-pro = []
beepy = []

### patches ###

[patch.crates-io.maitake]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

[patch.crates-io.mycelium-util]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

# Use the `mycelium-bitfield` crate from the Mycelium monorepo rather than
# crates.io.
# NOTE: this patch, unlike the patches for `maitake` and `mycelium-util`, (which
# are unpublished), is not *strictly* necessary, as `mycelium-bitfield` *is*
# published to crates.io. However, we may as well depend on the git version,
# since it's already in our dependency tree as a transitive dep of `maitake` ---
# having both a Git dep and a crates.io dep seems unfortunate.
[patch.crates-io.mycelium-bitfield]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

[patch.crates-io.cordyceps]
git = "https://github.com/hawkw/mycelium.git"
rev = "101a4abaa19afdd131b334a16d92c9fb4909c064"

[patch.crates-io.mnemos-alloc]
path = "../../source/alloc"

# NOTE: keep this patch in sync with the one in the main kernel workspace!
[patch.crates-io.bbq10kbd]
git = "https://github.com/hawkw/bbq10kbd"
branch = "eliza/async"
