[workspace]
resolver = "2"
members = [
    "./lichee-rv",
    "./mq-pro",
]

[patch.crates-io.maitake]
git = "https://github.com/hawkw/mycelium.git"
rev = "cbcfc62a6ea3646fb43f2c159cfdc19b3d932004"

[patch.crates-io.mycelium-util]
git = "https://github.com/hawkw/mycelium.git"
rev = "cbcfc62a6ea3646fb43f2c159cfdc19b3d932004"

[patch.crates-io.cordyceps]
git = "https://github.com/hawkw/mycelium.git"
rev = "cbcfc62a6ea3646fb43f2c159cfdc19b3d932004"

[patch.crates-io.mnemos-alloc]
path = "../../../source/alloc"
