[alias]
crowtty = "run --bin crowtty --release --"
melpomene = "run --bin melpomene --release --"
melpo = "melpomene"
forth3 = "run --bin f3repl --release --"

[build]
# Currently needed for `tokio-console` support.
rustflags = ["--cfg", "tokio_unstable"]

[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[unstable]
bindeps = true
