[workspace]
members = [
    "kernel",
    "abi",
    "mstd",
    "spitebuf",
    "melpomene",
]

[patch.crates-io.maitake]
git = "https://github.com/jamesmunns/mycelium.git"
rev = "833c343dcdf725b621ecdb6aae3873d984563a61"

[patch.crates-io.cordyceps]
git = "https://github.com/jamesmunns/mycelium.git"
rev = "833c343dcdf725b621ecdb6aae3873d984563a61"

[patch.crates-io.mnemos-alloc]
git = "https://github.com/tosc-rs/mnemos-alloc"
rev = "9aa7bf59c85d7d02f179f5b5171dae4cff00affd"
